### ISSUE TITLE
Support for git protocol

### ISSUE THREAD

**Issue by zomars** [mheap/submodule-sync-action#2]
It seems like this action only support submodules with the HTTP protocol:

```
Run mheap/submodule-sync-action@v1
[8](https://github.com/my-org/my-repo/runs/5760535082?check_suite_focus=true#step:2:8)
(node:1526) UnhandledPromiseRejectionWarning: Error: Non-GitHub submodule found. Unable to process 'git@github.com:my-org/private-repo.git'
[9](https://github.com/my-org/my-repo/runs/5760535082?check_suite_focus=true#step:2:9)
    at action (/home/runner/work/_actions/mheap/submodule-sync-action/v1/dist/index.js:38:11)
[10](https://github.com/my-org/my-repo/runs/5760535082?check_suite_focus=true#step:2:10)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
[11](https://github.com/my-org/my-repo/runs/5760535082?check_suite_focus=true#step:2:11)
(node:1526) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
[12](https://github.com/my-org/my-repo/runs/5760535082?check_suite_focus=true#step:2:12)
(node:1526) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by mheap** [comment]
This is now released as `v1.2.0`. Apologies for the delay, it slipped through the net somehow
